let S=JSON.parse(localStorage.historaa||'{"xp":0,"coins":0}');const $=x=>document.querySelector(x);function save(){localStorage.historaa=JSON.stringify(S);$('#xp').textContent=S.xp}save();
function page(id){document.querySelectorAll('section').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
const C={India:['🇮🇳','Agra • Hampi • Nalanda'],Egypt:['🇪🇬','Giza • Luxor • Alexandria'],Greece:['🇬🇷','Athens • Delphi • Olympia'],China:['🇨🇳','Xi’an • Beijing • Dunhuang'],Rome:['🇮🇹','Rome • Pompeii • Ostia'],Maya:['🇲🇽','Chichén Itzá • Tikal • Palenque'],Japan:['🇯🇵','Nara • Kyoto • Himeji']};
const pos=[[43,67],[58,44],[43,32],[76,34],[31,44],[14,59],[83,64]];Object.keys(C).forEach((n,k)=>{$('#mapbox').innerHTML+=`<button class="pin" style="left:${pos[k][0]}%;top:${pos[k][1]}%" onclick="showC('${n}')">${C[n][0]}<small>${n}</small></button>`});function showC(n){$('#info').innerHTML=`<h2>${C[n][0]} ${n}</h2><p>Explore ${C[n][1]} through the illustrated comic, then test yourself in the quiz.</p><button class="gold" onclick="selectCiv('${n}');page('comics')">Open ${n} Comic →</button>`;S.xp+=10;save()}
let comics=[],cp=1,cc='India';fetch('data/comics.json').then(r=>r.json()).then(d=>{comics=d;const sel=$('#civSelect');Object.keys(C).forEach(n=>sel.innerHTML+=`<option>${n}</option>`);selectCiv('India')}).catch(()=>{$('#ct').textContent='Comic data could not load';});
function selectCiv(n){cc=n;cp=1;renderComic()}function comic(d){cp=Math.max(1,Math.min(100,cp+d));renderComic()}function jumpComic(){cp=Math.max(1,Math.min(100,Number($('#pageJump').value)||1));renderComic()}function renderComic(){let pages=comics.filter(x=>x.civ===cc);if(!pages.length)return;let p=pages[(cp-1)%pages.length];$('#cp').textContent=cp;$('#ct').textContent=`${cc} — ${p.pageTitle}`;$('#cx').textContent=p.text;$('#cifact').textContent=`📜 Historical note: This page is based on established historical context. Where evidence is limited, HISTORAA avoids presenting invented dialogue as fact.`;$('#comicImg').src=p.image;$('#pageJump').value=cp;$('#civSelect').value=cc;}
let women=[],wp=1;fetch('data/women.json').then(r=>r.json()).then(d=>{women=d;renderWoman()});function woman(d){wp=Math.max(1,Math.min(50,wp+d));renderWoman()}function renderWoman(){if(!women.length)return;let w=women[wp-1];$('#wpage').textContent=`PAGE ${wp} / 50`;$('#wname').textContent=`${w.woman} — ${w.stage}`;$('#wstory').textContent=w.text;$('#wfact').textContent=`${w.country} • ${w.years} • Historical focus: ${w.stage}`;$('#wpic').src=w.image}
let questions=[],qi=0,answered=false;fetch('data/questions.json').then(r=>r.json()).then(d=>{questions=d.sort(()=>Math.random()-.5);$('#quizCount').textContent=`${questions.length} questions loaded • Every wrong answer gives a hint instead of a harsh penalty.`;loadQ()}).catch(e=>$('#q').textContent='Quiz data failed to load. Check that data/questions.json is uploaded.');
function loadQ(){if(!questions.length)return;answered=false;let x=questions[qi];$('#qnum').textContent=`QUESTION ${qi+1} / ${questions.length} • ${x.civ}`;$('#q').textContent=x.question;$('#answers').innerHTML=x.options.map((o,k)=>`<button class="ans" onclick="answer(${k})">${String.fromCharCode(65+k)}. ${o}</button>`).join('');$('#feedback').textContent='';$('#nextBtn').disabled=true}
function answer(k){if(answered)return;answered=true;let x=questions[qi];document.querySelectorAll('.ans').forEach((b,i)=>b.disabled=true);if(k===x.answer){S.xp+=100;$('#feedback').innerHTML=`<b>🎉 Correct! +100 XP</b><br>Great work. Keep exploring the story behind the answer.`}else{$('#feedback').innerHTML=`<b>🤔 Not quite — no penalty.</b><br>💡 Hint: ${x.hint}<br>🧩 Re-read the question and use the clue to learn the answer.`}$('#nextBtn').disabled=false;save()}function showHint(){let x=questions[qi];if(x)$('#feedback').innerHTML=`💡 Hint: ${x.hint}`};function nextQ(){qi=(qi+1)%questions.length;loadQ()}
const B=[['FOUR + GET + IT = ?','forget it','Say the three parts as one phrase.'],['STAND\nI\nSTAND','i understand','Look at where I is placed.'],['cycle + cycle + cycle = ?','tricycle','How many cycles are there?'],['What has keys but cannot open a door?','piano','It can make music.']];let bd=Math.floor(Date.now()/86400000),bp=B[bd%B.length];$('#bdate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#bq').innerText=bp[0];function hintBrain(){$('#bf').innerHTML='🔎 Hint: '+bp[2]}function solveBrain(){let a=$('#ba').value.trim().toLowerCase();if(a===bp[1]){S.xp+=100;$('#bf').innerHTML='🎉 Brilliant! +100 XP'}else $('#bf').innerHTML='🤔 Not quite. You get a clue, not a penalty!';save()}
const cards=[['🇮🇳','Taj Mahal'],['🇪🇬','Great Pyramid'],['🇬🇷','Parthenon'],['🇨🇳','Great Wall'],['🇮🇹','Colosseum'],['🇲🇽','Chichén Itzá'],['🇯🇵','Himeji Castle'],['👩','Women Who Changed History']];$('#cardsbox').innerHTML=cards.map(c=>`<article class="card"><h1>${c[0]}</h1><h3>${c[1]}</h3><p>Explore its history to collect the card.</p></article>`).join('');
let cv=$('#canvas'),cx=cv.getContext('2d'),g=null,keys={};onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))e.preventDefault();keys[e.key]=1};onkeyup=e=>keys[e.key]=0;function bind(id,key){let b=$(id);['pointerdown','touchstart'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();keys[key]=1},{passive:false}));['pointerup','pointercancel','touchend','touchcancel','pointerleave'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();keys[key]=0},{passive:false}))}bind('#leftBtn','ArrowLeft');bind('#rightBtn','ArrowRight');bind('#jumpBtn','ArrowUp');let paused=false;function startGame(){g={x:100,y:320,v:0,t:0,coins:0};paused=false;requestAnimationFrame(run)}function pauseGame(){paused=!paused;if(!paused&&g)requestAnimationFrame(run)}function run(){if(!g||paused)return;g.t++;g.v+=.7;g.y+=g.v;if(g.y>320)g.y=320;if((keys.ArrowUp||keys[' '])&&g.y===320)g.v=-12;g.x+=(keys.ArrowRight?5:0)-(keys.ArrowLeft?5:0);g.x=Math.max(30,Math.min(850,g.x));let coinX=(g.t*3)%850+20;if(Math.abs(g.x-coinX)<35&&g.y>250){g.coins++;S.xp+=10;save()}cx.clearRect(0,0,900,400);cx.fillStyle='#5b351f';cx.fillRect(0,0,900,400);cx.fillStyle='#b98b55';cx.fillRect(0,370,900,30);cx.font='40px serif';cx.fillText('🏛️',100,150);cx.fillText('🗿',700,170);cx.fillText('🏃',g.x,g.y+40);cx.font='30px serif';cx.fillText('🪙',coinX,300);cx.font='16px Arial';cx.fillStyle='white';cx.fillText('TREASURE: '+g.coins+' • XP: '+S.xp,20,25);requestAnimationFrame(run)}
