let S=JSON.parse(localStorage.historaa||'{"xp":0,"coins":0}');const $=x=>document.querySelector(x);function save(){localStorage.historaa=JSON.stringify(S);$("#xp").textContent=S.xp}save();
function page(id){document.querySelectorAll("section").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");scrollTo(0,0)}
const C={India:["🇮🇳","Agra • Hampi • Nalanda"],Egypt:["🇪🇬","Giza • Luxor • Alexandria"],Greece:["🇬🇷","Athens • Delphi • Olympia"],China:["🇨🇳","Xi'an • Beijing • Dunhuang"],Rome:["🇮🇹","Rome • Pompeii • Ostia"],Maya:["🇲🇽","Chichén Itzá • Tikal • Palenque"],Japan:["🇯🇵","Nara • Kyoto • Himeji"]};
let pos=[[43,67],[58,44],[43,32],[76,34],[31,44],[14,59],[83,64]],i=0;Object.entries(C).forEach(([n,v],k)=>{$("#mapbox").innerHTML+=`<button class="pin" style="left:${pos[k][0]}%;top:${pos[k][1]}%" onclick="showC('${n}')">${v[0]}<small>${n}</small></button>`});function showC(n){let c=C[n];$("#info").innerHTML=`<h2>${c[0]} ${n}</h2><p>Discover <b>${c[1]}</b>. Unlock comics, monuments, women, cards, quizzes and treasure locations.</p><button class="gold" onclick="page('comics')">Enter World →</button>`;S.xp+=25;save()}
let cp=1,cc="India";function comic(d){cp=Math.max(1,Math.min(100,cp+d));let c=C[cc]||C.India;$("#cp").textContent=cp;$("#comicArt").textContent=c[0];$("#ct").textContent=`${cc} — Chapter ${Math.ceil(cp/10)}`;$("#cx").textContent=cp===1?"Across rivers and fertile plains, communities grew into cities, creating art, trade, knowledge and traditions.":`Comic page ${cp}: a historical moment, person, place, invention or cultural tradition. This prototype scales to 100 pages per civilization.`}
const W=[["🇮🇳","Rani Lakshmibai","A leader remembered for her role in the 1857 uprising."],["🇪🇬","Hatshepsut","One of ancient Egypt's most prominent female rulers."],["🇬🇷","Aspasia","A woman associated with classical Athens and ancient literary sources."],["🇨🇳","Wu Zetian","The only woman traditionally recognized as emperor in China's imperial history."],["🇮🇹","Livia Drusilla","A powerful figure in the early Roman imperial household."],["🇲🇽","Lady Six Sky","A powerful Maya ruler known from inscriptions."],["🇯🇵","Murasaki Shikibu","Author traditionally associated with The Tale of Genji."]];let wi=0,wp=1;function woman(){wp=wp>=7?1:wp+1;let w=W[wi++%W.length];$("#wpic").textContent=w[0];$("#wpage").textContent=`PAGE ${Math.min(50,wp)} / 50`;$("#wname").textContent=w[1];$("#wstory").textContent=w[2]+" Comic pages can expand this into childhood, achievements, challenges and legacy.";$("#wfact").textContent="📜 Historical evidence and dramatized comic reconstruction should be clearly distinguished.";S.xp+=50;save()}
const Q=[["Which civilization is associated with the Nile River?",["Egypt","Rome","Maya","Japan"],0,"Think of northeastern Africa."],["The Taj Mahal is located in which country?",["India","China","Italy","Mexico"],0,"It is in Agra."],["Chichén Itzá is associated with which civilization?",["Maya","Roman","Egyptian","Japanese"],0,"Think of Mesoamerica."],["Which ancient Greek site was famous for its oracle?",["Delphi","Giza","Hampi","Nara"],0,"It is in Greece."]];let qi=0;function loadQ(){let q=Q[qi++%Q.length];$("#q").textContent=q[0];$("#answers").innerHTML=q[1].map((x,k)=>`<button class="ans" onclick="answer(${k},${q[2]})">${String.fromCharCode(65+k)}. ${x}</button>`).join("");$("#feedback").textContent=""}function answer(k,ok){if(k===ok){S.xp+=100;$("#feedback").innerHTML="🎉 Correct! +100 XP";}else $("#feedback").innerHTML="🤔 Not quite! 🔎 Hint: "+Q[(qi-1)%Q.length][3]+"<br>🧩 Try again — mistakes unlock clues.";save()}loadQ();
const B=[["FOUR + GET + IT = ?","Rebus / wordplay","forget it","Say the three parts as one phrase.","FOUR + GET + IT → FORGET IT."],["STAND\nI\nSTAND","Rebus / wordplay","i understand","Look at where I is placed.","I is UNDER STAND → I UNDERSTAND."],["cycle + cycle + cycle = ?","Word puzzle","tricycle","How many cycles are there?","Three cycles = TRI + CYCLE."],["What has keys but cannot open a door?","Lateral thinking","piano","It can make music.","A piano has keys but does not unlock doors."]];let bd=Math.floor(Date.now()/86400000),bp=B[bd%B.length];$("#bdate").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});$("#bq").innerText=bp[0];function hintBrain(){$("#bf").innerHTML="🔎 Hint: "+bp[3]}function solveBrain(){let a=$("#ba").value.trim().toLowerCase();if(a===bp[2]){S.xp+=100;$("#bf").innerHTML="🎉 Brilliant! "+bp[4]+"<br>+100 XP";let x=JSON.parse(localStorage.historaaBrain||'{"d":-1,"s":0}');if(x.d!==bd){x.s=x.d===bd-1?x.s+1:1;x.d=bd;localStorage.historaaBrain=JSON.stringify(x)}$("#streak").textContent=x.s}else{$("#bf").innerHTML="🤔 Not quite. You get a clue, not a penalty! Click Hint."}save()}let x=JSON.parse(localStorage.historaaBrain||'{"d":-1,"s":0}');$("#streak").textContent=x.s;
const cards=[["🇮🇳","Taj Mahal"],["🇪🇬","Great Pyramid"],["🇬🇷","Parthenon"],["🇨🇳","Great Wall"],["🇮🇹","Colosseum"],["🇲🇽","Chichén Itzá"],["🇯🇵","Himeji Castle"],["👩","Women Who Changed History"]];$("#cardsbox").innerHTML=cards.map(c=>`<article class="card"><h1>${c[0]}</h1><h3>${c[1]}</h3><p>Collect this card by exploring its civilization.</p></article>`).join("");
let cv=$("#canvas"),cx=cv.getContext("2d"),g=null,keys={};
function setKey(k,v){keys[k]=v}
onkeydown=e=>{if(["ArrowLeft","ArrowRight","ArrowUp"," "].includes(e.key))e.preventDefault();setKey(e.key,1)};
onkeyup=e=>setKey(e.key,0);
function bindHold(id,key){const b=$(id);if(!b)return;const down=e=>{e.preventDefault();setKey(key,1)};const up=e=>{e.preventDefault();setKey(key,0)};["touchstart","pointerdown"].forEach(ev=>b.addEventListener(ev,down,{passive:false}));["touchend","touchcancel","pointerup","pointerleave"].forEach(ev=>b.addEventListener(ev,up,{passive:false}));}
bindHold("#leftBtn","ArrowLeft");bindHold("#rightBtn","ArrowRight");bindHold("#jumpBtn","ArrowUp");
let gamePaused=false;
function startGame(){g={x:100,y:320,v:0,s:0,t:0,coins:0};gamePaused=false;requestAnimationFrame(run)}
function pauseGame(){gamePaused=!gamePaused;if(!gamePaused&&g)requestAnimationFrame(run)}
function run(){if(!g||gamePaused)return;g.t++;g.v+=.7;g.y+=g.v;if(g.y>320)g.y=320;
if((keys.ArrowUp||keys[" "])&&g.y===320)g.v=-12;
g.x+=(keys.ArrowRight?5:0)-(keys.ArrowLeft?5:0);g.x=Math.max(30,Math.min(850,g.x));
const coinX=((g.t*3)%850)+20,artifactX=((g.t*5)%850)+20;
if(Math.abs(g.x-coinX)<35&&g.y>250){g.coins++;S.xp+=10;save()}
cx.clearRect(0,0,900,400);cx.fillStyle="#0d1730";cx.fillRect(0,0,900,400);cx.fillStyle="#a87d45";cx.fillRect(0,370,900,30);
cx.font="40px serif";cx.fillText("🏛️",100,150);cx.fillText("🗿",700,170);cx.fillText("🏃",g.x,g.y+40);
cx.font="30px serif";cx.fillText("🪙",coinX,300);cx.fillText("🏺",artifactX,230);
cx.font="16px Arial";cx.fillStyle="white";cx.fillText("TREASURE: "+g.coins+"   •   XP: "+S.xp,20,25);
requestAnimationFrame(run)}
